pipeline {
        agent any
        stages { 
            stage('Example') {
                steps {
    timestamps {
                    echo 'Hello World'
                }
            }
        }
    }
}
